version: 2
updates:
    -
        package-ecosystem: "pip"
        directory: "/"
        schedule:
            interval: "daily"
        allow:
            - dependency-type: "production"
        open-pull-requests-limit: 5
        commit-message:
            prefix: "fix"
            prefix-development: "chore"
            include: "scope"
